version: '3'
services:
  web:
    build: .
    env_file:
      - env/${ENV}.env
    ports:
      - ${WEB_PORT}:8000
    environment:
      ENV: ${ENV}
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data/${ENV}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: doc_store
      POSTGRES_PASSWORD: password
